ArquiWeb/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ArquiWeb.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

ArquiWeb/Pages/ChangeGreeting.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ArquiWeb.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web_App_Arqui.Pages
{
    public class ChangeGreetingModel : PageModel
    {
        private readonly IConsumer consumer;

        [BindProperty]
        public string Greeting { set; get; }
        public void OnGet()
        {

        }
        public ChangeGreetingModel(IConsumer consumer)
        {
            this.consumer = consumer;
        }
        public async Task<IActionResult> OnPostAsync()
        {
            bool result = await consumer.ExecuteCommandAsync(Greeting);
            if (result)
            {
                return RedirectToPage("/MailboxMenu");
            }
            return Page();
        }
    }
}

ArquiWeb/Pages/ChangePasscode.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ArquiWeb.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web_App_Arqui.Pages
{
    public class ChangePasscodeModel : PageModel
    {
        private readonly IConsumer consumer;

        public ChangePasscodeModel(IConsumer consumer)
        {
            this.consumer = consumer;
        }

        [BindProperty]
        public string Passcode { set; get; }
        public void OnGet()
        {

        }
        public async Task<IActionResult> OnPostAsync()
        {
            bool result = await consumer.ExecuteCommandAsync(Passcode);
            if (result)
            {
                return RedirectToPage("/MailboxMenu");
            }
            return Page();
        }
    }
}

ArquiWeb/Pages/Config.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ArquiWeb.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ArquiWeb.Pages
{
    public class ConfigModel : PageModel
    {
        private readonly IConsumer consumer;

        public ConfigModel(IConsumer consumer)
        {
            this.consumer = consumer;
        }

        [BindProperty]
        public string Url { set; get; }
        public string Error { set; get; }
        public void OnGet()
        {

        }
        public async Task<IActionResult> OnPostAsync()
        {
            consumer.SetUrl(Url);
            bool result = await consumer.Ping();
            if (result)
            {
                return RedirectToPage("/Connect");
            }
           Error = "No se pudo establecer conexion";
            return Page();
        }
    }
}

ArquiWeb/Pages/Connect.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ArquiWeb.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web_App_Arqui.Pages
{
    public class InitialPromtModel : PageModel
    {
        [BindProperty]
        public string Message { set; get; }
        [BindProperty]
        public string IDMailbox { set; get; }
        private static string MessageInitial = "Ingrese el numero de buzon y presione llamar";
        private static string MessageErrorConnection = "Numero de buzon incorrecto. Intentelo de nuevo!";
        private readonly IConsumer consumer;

        public InitialPromtModel(IConsumer consumer)
        {
            this.consumer = consumer;
        }

        public void OnGet()
        {
            Message = MessageInitial;
        }
        public async Task<IActionResult> OnPost()
        {
            bool result = await consumer.ExecuteCommandAsync(IDMailbox);
            if (result)
                return RedirectToPage("/Recording");
            Message = MessageErrorConnection;
            return Page();
        }

    }
}

ArquiWeb/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ArquiWeb.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

ArquiWeb/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ArquiWeb.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ArquiWeb/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ArquiWeb.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ArquiWeb.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IConsumer consumer;

        public IndexModel(IConsumer consumer)
        {
            this.consumer = consumer;
        }
        public IActionResult OnGet()
        {
            var verify = consumer.HasUrl();
            if (verify)
            {
                return RedirectToPage("/Config");
            }
            return RedirectToPage("/Connect");
        }
    }
}

ArquiWeb/Pages/MailboxMenu.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ArquiWeb.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web_App_Arqui.Pages
{
    public class MailboxMenuModel : PageModel
    {
        private readonly IConsumer consumer;

        public MailboxMenuModel(IConsumer consumer)
        {
            this.consumer = consumer;
        }

        public void OnGet()
        {

        }
        public async Task<IActionResult> OnPostListenAsync()
        {
            bool result = await consumer.ExecuteOptionAsync("1");
            if (result)
            {
                return RedirectToPage("/MessageMenu");
            }
            return Page();
            
        }
        public async Task<IActionResult> OnPostPasscodeAsync()
        {
            bool result = await consumer.ExecuteOptionAsync("2");
            if (result)
            {
                return RedirectToPage("/ChangePasscode");
            }
            return Page();
        }
        public async Task<IActionResult> OnPostGreetingAsync()
        {
            bool result = await consumer.ExecuteOptionAsync("3");
            if (result)
            {
                return RedirectToPage("/ChangeGreeting");
            }
            return Page();
        }
        public async Task<IActionResult> OnPostExitAsync()
        {
            bool result = await consumer.ExecuteOptionAsync("H");
            if (result)
            {
                return RedirectToPage("/Connect");
            }
            return Page();
        }
    }
}

ArquiWeb/Pages/MessageMenu.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ArquiWeb.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web_App_Arqui.Pages
{
    public class MessageMenuModel : PageModel
    {
        private readonly IConsumer consumer;

        [BindProperty]
        public string Message { set; get; }
        [BindProperty]
        public string CurrentMessageText { set; get; }
        public string Error { set; get; }
        public MessageMenuModel(IConsumer consumer)
        {
            this.consumer = consumer;
        }
        public void OnGet()
        {

        }
        public async Task<IActionResult> OnPostListenAsync()
        {
            bool executed = await consumer.ExecuteOptionAsync("1");
            string result = await consumer.GetCurrentMessage();
                CurrentMessageText = result;
                Message = "Mensaje actual";
                Error = "";
                return Page();
        }
        public async Task<IActionResult> OnPostSaveAsync()
        {
            bool result = await consumer.ExecuteOptionAsync("2");
            if (result) { 
                Error = "";
            return Page();
            }
            Error = "Algo salio mal";
            return Page();

        }
        public async Task<IActionResult> OnPostDeleteAsync()
        {
            bool result = await consumer.ExecuteOptionAsync("3");
            if (result) { 
                Error = "";
            return Page();
        }
        Error = "Algo salio mal";
            return Page();
        }
        
        public async Task<IActionResult> OnPostMailBoxMenuAsync()
        {
            bool result = await consumer.ExecuteOptionAsync("4");
            if (result)
            {
                Error = "";
                return RedirectToPage("/MailBoxMenu");
            }
            Error = "Algo salio mal";
            return Page();
        }
        


    }
}

ArquiWeb/Pages/Recording.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ArquiWeb.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web_App_Arqui.Pages
{
    public class RecordingModel : PageModel
    {
        private readonly IConsumer consumer;

        [BindProperty]
        public string Message { set; get; }

        [BindProperty]
        public string Passcode { set; get; }
        [BindProperty]
        public string Error { set; get; }
        [BindProperty]
        public string Greeting { set; get; }
        public RecordingModel(IConsumer consumer)
        {
            this.consumer = consumer;
        }
        public async Task OnGetAsync()
        {
            Greeting = await consumer.GetGreeting();
        }
        public async Task<IActionResult> OnPostSendMessageAsync()
        {
            //añadir mensage
            bool result = await consumer.ExecuteCommandMessageAsync(Message);
            if (result)
                return RedirectToPage("/Connect");
            Error = "Algo sucedio";
            return Page();
            
        }
        public async Task<IActionResult> OnPostLoginAsync()
        {
            //estado
            bool result = await consumer.ExecuteCommandAsync(Passcode);
            if (result)
                return RedirectToPage("/MailboxMenu");
            Error = "Codigo de acceso incorrecto, vuelva a intentar!";
            return Page();
        }
        public async Task<IActionResult> OnPostExit()
        {
            //estado
            bool result = await consumer.ExecuteOptionAsync("H");
            if (result)
                return RedirectToPage("/Connect");
            Error = "Codigo de acceso incorrecto, vuelva a intentar!";
            return Page();
        }
    }
 
}

ArquiWeb/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

ArquiWeb/Pages/ChangeGreeting.cshtml
@page
@model Web_App_Arqui.Pages.ChangeGreetingModel
@{
    ViewData["Title"] = "ChangeGreeting";
}

<h2>Cambiar saludo</h2>
<h3>Ingrese su nuevo saludo y presione guardar</h3>
<div class="row">
    <div class="col-lg-5">
        <form method="post" autocomplete="off">
            <input asp-for="Greeting" class="form-control" />
            <br />
            <input type="submit" value="Guardar" class="btn btn-success" />
        </form>
    </div>
</div>

ArquiWeb/Pages/ChangePasscode.cshtml
@page
@model Web_App_Arqui.Pages.ChangePasscodeModel
@{
    ViewData["Title"] = "ChangePasscode";
}

<h2>Cambiar codigo de acceso</h2>
<h3>Ingrese su nuevo codigo de acceso y presione guardar</h3>
<div class="row">
    <div class="col-lg-5">
        <form method="post" autocomplete="off">
            <input asp-for="Passcode" class="form-control" />
            <br />
            <input type="submit" value="Guardar" class="btn btn-success" />
        </form>
    </div>
</div>

ArquiWeb/Pages/Config.cshtml
@page
@model ArquiWeb.Pages.ConfigModel
@{
    ViewData["Title"] = "Config";
}

<h2>Configuracion</h2>
<h3>Ingrese la URL de la api</h3>

<div class="row">
    <div class="col-lg-5">
            <h3>@Model.Error</h3>
        <form method="post">
            <input class="form-control" type="text" asp-for="Url" />
            <br />
            <input type="submit" class="btn btn-success" value="Guardar" />
        </form>
    </div>
</div>

ArquiWeb/Pages/Connect.cshtml
@page
@model Web_App_Arqui.Pages.InitialPromtModel
@{
    ViewData["Title"] = "InitialPromt";
}

<h3>@Model.Message</h3>
<div class="row">
    <div class="col-lg-5">
        <form method="post" autocomplete="off">

            <textarea readonly asp-for="IDMailbox" style="font-weight: bold; font-size:24px" type="text" class="form-control"></textarea>
            @Html.Partial("Phone")
            <input type="submit" class="btn btn-success" style='width:100px; height:100px' value="Llamar" />
        </form>
    </div>
    <div class="col-lg-5">

    </div>
</div>


@Html.Partial("ScriptsPhone", "IDMailbox")

ArquiWeb/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ArquiWeb/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core Razor Pages</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?linkid=852130">Working with Razor Pages.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure App Service</a></li>
        </ul>
    </div>
</div>

ArquiWeb/Pages/MailboxMenu.cshtml
@page
@model Web_App_Arqui.Pages.MailboxMenuModel
@{
    ViewData["Title"] = "MailboxMenu";
}

<h2>Menu Buzón</h2>
<div class="row">
    <div class="col-lg-5">
        <div class="row">
            <form asp-page-handler="Listen" method="post">
                <input class="btn btn-primary" type="submit" value="Escuchar mensajes" />
            </form>

        </div>
        <br />
        <div class="row">
            <form asp-page-handler="Passcode" method="post">
                <input class="btn btn-primary" type="submit" value="Cambiar codigo de acceso" />
            </form>
        </div>
        <br />
        <div class="row">
            <form asp-page-handler="Greeting" method="post">
                <input class="btn btn-primary" type="submit" value="Cambiar saludo" />
            </form>
        </div>
        <div class="row">
            <br />
            <form asp-page-handler="Exit" method="post">
                <input class="btn btn-danger" type="submit" value="Colgar" />
            </form>
        </div>
        </div>
    </div>

ArquiWeb/Pages/MessageMenu.cshtml
@page
@model Web_App_Arqui.Pages.MessageMenuModel
@{
    ViewData["Title"] = "MessageMenu";
}

<h2>Menu de mensajes</h2>
<h2>@Model.Error</h2>
<div class="row">
    <div class="col-lg-5">
        <form asp-page-handler="Listen">
            <input type="submit" class="btn btn-primary" value="Escuchar mensaje actual" />
        </form>
        <br />
        <form asp-page-handler="Save">
            <input type="submit" class="btn btn-primary" value="Guardar mensaje actual" />
        </form>
        <br />
        <form asp-page-handler="Delete">
            <input type="submit" class="btn btn-primary" value="Eliminar mensaje actual" />
        </form>
        <br />
        <form asp-page-handler="MailBoxMenu">
            <input type="submit" class="btn btn-primary" value="Ir a Menu Buzon" />
        </form>
    </div>
    <div class="col-lg-5">
        <h3>@Model.Message</h3>
            
        
        <br />

        <h4>@Model.CurrentMessageText</h4>
    </div>
</div>

ArquiWeb/Pages/Phone.cshtml
<br />

<table>
    <tr>
        <th><button type="button" class="btn btn-primary" style='width:100px; height:100px' value="1">1</button></th>
        <th><button type="button" class="btn btn-primary" style='width:100px; height:100px' value="2">2</button></th>
        <th><button type="button" class="btn btn-primary" style='width:100px; height:100px' value="3">3</button></th>
    </tr>
    <tr>
        <th><button type="button" class="btn btn-primary" style='width:100px; height:100px' value="4">4</button></th>
        <th><button type="button" class="btn btn-primary" style='width:100px; height:100px' value="5">5</button></th>
        <th><button type="button" class="btn btn-primary" style='width:100px; height:100px' value="6">6</button></th>
    </tr>
    <tr>
        <th><button type="button" class="btn btn-primary" style='width:100px; height:100px' value="7">7</button></th>
        <th><button type="button" class="btn btn-primary" style='width:100px; height:100px' value="8">8</button></th>
        <th><button type="button" class="btn btn-primary" style='width:100px; height:100px' value="9">9</button></th>
    </tr>
    <tr>
        <th><button onclick="cleanAll();" type="button" class="btn btn-primary" style='width:100px; height:100px'>Borrar todo</button></th>
        <th><button type="button" class="btn btn-primary" style='width:100px; height:100px' value="0">0</button></th>
        <th><button onclick="clean();" type="button" class="btn btn-primary" style='width:100px; height:100px'>Borrar</button></th>
    </tr>
</table>

<br />

ArquiWeb/Pages/Recording.cshtml
@page
@model Web_App_Arqui.Pages.RecordingModel
@{
    ViewData["Title"] = "Recording";
}
<h3>@Model.Error</h3>
<div class="row">
    <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#Message">Mensaje</a></li>
        <li><a data-toggle="tab" href="#Login">Iniciar sesion</a></li>
    </ul>
    <div class="tab-content">
        <div id="Message" class="tab-pane fade in active">
            <div class="col-lg-5">
                <h2>@Model.Greeting</h2>
                <form asp-page-handler="SendMessage" method="post" autocomplete="off">
                    <textarea asp-for="Message" class="form-control"></textarea>

                    <input type="submit" class="btn btn-success" value="Enviar" />
                </form>
                <form asp-page-handler="Exit" method="post">
                    <input type="submit" class="btn btn-danger" value="Colgar" />
                </form>
            </div>
        </div>
        <div id="Login" class="tab-pane fade">
            <h3>Ingrese su código de acceso</h3>

            <div class="col-lg-5">
                <form asp-page-handler="Login" method="post" autocomplete="off">
                    <textarea readonly asp-for="Passcode" style="font-weight: bold; font-size:24px" type="text" class="form-control"></textarea>
                    @Html.Partial("Phone")
                    <input type="submit" class="btn btn-success" value="Ingresar" />
                </form>
                <form asp-page-handler="Exit" method="post">
                    <input type="submit" class="btn btn-danger" value="Colgar" />
                </form>
            </div>
        </div>
    </div>
</div>
@Html.Partial("ScriptsPhone", "Passcode")

ArquiWeb/Pages/ScriptsPhone.cshtml
@model string

@{ 
    var input = "#" + Model;
}

<script src="~/lib/jquery/dist/jquery.js"></script>

<script>
    var button = $("button");
    var input = $("@input");
    var clean = function () {
        var values = input.val();
        values = values.substring(0, values.length - 1);
        input.val(values);
    };

    var cleanAll = function () {
        input.val("");
    };
    button.click(function () {
        var num = this.value;
        var values = input.val();
        input.val(values+num);
    });
</script>

ArquiWeb/Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ArquiWeb</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - ArquiWeb</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>